---
apiVersion: v1
kind: Service
metadata:
  name: todos-service
  labels:
    app: todos-edge
spec:
  ports:
  - port: 9999
    targetPort: 9999
    name: boot
  selector:
    app: todos-edge
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-edge
  template:
    metadata:
      name: todos-edge
      labels:
        app: todos-edge
    spec:
      containers:
      - image: triathlonguy/todos-edge:latest
        name: todos-edge
        ports:
        - containerPort: 9999
          protocol: TCP
        env:
        - name: TODOS_API_ENDPOINT
          value: "http://todos-api.default.svc.cluster.local:80"
        - name: TODOS_UI_ENDPOINT
          value: "http://todos-webui.default.svc.cluster.local:8080"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-edge-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: todos-service
              servicePort: 9999
  tls:
    - hosts:
        - localhost
      secretName: ingress-tls