---
apiVersion: v1
kind: Service
metadata:
  name: todos-redis
  labels:
    app: todos-redis
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: boot
  selector:
    app: todos-redis
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-redis-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: todos-redis
              servicePort: 8888
  tls:
    - hosts:
        - localhost
      secretName: ingress-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-redis
  template:
    metadata:
      name: todos-redis
      labels:
        app: todos-redis
    spec:
      containers:
        - image: triathlonguy/todos-redis:latest
          name: todos-redis
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: SPRING_REDIS_HOST
              value: "todo-redis-instance-master.default.svc.cluster.local"
            - name: SPRING_REDIS_PASSWORD
              value: "topsecret"
